# Generated by Django 5.2.4 on 2025-08-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='vip',
            field=models.BooleanField(default=False),
        ),
    ]
